server {
  listen 80;
  listen [::]:80;

  server_name staging.limoneo.com;

  root /var/www/limoneo-staging/current/public;
  index index.php;

  # ACME challenge (certbot)
  location ^~ /.well-known/acme-challenge/ {
    allow all;
    default_type text/plain;
    root /var/www/limoneo-staging/current/public;
  }

  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ~ \.php$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:/run/php/php8.3-fpm.sock;
  }

  location ~ /\. {
    deny all;
  }
}
